export const APP_CONSTANTS = new Map<string, string | Array<string>>([
  ["SEARCH_BOX_PLACEHOLDER", "Search for a Restaurant by Name, Cuisine, or Location"],
  ["REVIEWS_LABEL", "reviews"],
  ["STAR_RATING_LABEL", "& more"],
  ["DELETE_RESTAURANT", "delete"],
  ["ADD_RESTAURANT", "add"],
  ["CANCEL_RESTAURANT", "cancel"],
  ["CANCEL_BUTTON_LABEL", "Cancel"],
  ["DELETE_BUTTON_LABEL", "Delete"],
  ["ADD_BUTTON_LABEL", "Add"],
  ["INDEX_NAME", "restaurants"],
  ["RESTAURANT_NAME_LABEL", "Name"],
  ["RESTAURANT_ADDRESS_LABEL", "Address"],
  ["RESTAURANT_FOOD_TYPE_LABEL", "Food Type"],
  ["RESTAURANT_PRICE_LABEL", "Restaurant's Price Range"],
  ["RESTAURANT_IMAGE_LABEL", "Upload Image"],
  ["RADIO_OPTION_LESS_30", "$30 and Under"],
  ["RADIO_OPTION_BW_31_AND_50", "$31 to $50"],
  ["RADIO_OPTION_OVER_50", "$50 and over"],
  ["RESTAURANT_PRICE_LEGEND", "Select a price range for the restaurant"],
  ["NAME_REQUIRED_ERROR_MSG", "Please enter a name"],
  ["ADDRESS_REQUIRED_ERROR_MSG", "Please enter the address"],
  ["FOOD_TYPE_REQUIRED_ERROR_MSG", "Please enter food type"],
  ["IMAGE_REQUIRED_ERROR_MSG", "Please upload an image"],
  ["FOOD_TYPE_OPTIONS", [
    "Kosher",
    "Wild Game",
    "Regional Mexican",
    "Syrian",
    "Austrian",
    "Low Country",
    "Burmese",
    "Southeast Asian",
    "Modern Australian",
    "Afghan",
    "Eurasian",
    "Prime Rib",
    "Sicilian",
    "Filipino",
    "Hawaii Regional Cuisine",
    "Polynesian",
    "Puerto Rican",
    "Hibachi",
    "Wine Bar",
    "Eastern European",
    "Korean",
    "Contemporary Indian",
    "Russian",
    "Vegetarian",
    "Australian",
    "Lebanese",
    "Swiss",
    "Middle Eastern",
    "Vegan",
    "South African",
    "Ethiopian",
    "Fondue",
    "Contemporary Mexican",
    "Traditional Mexican",
    "Brazilian",
    "Mexican / Southwestern",
    "Contemporary Southern",
    "Peruvian",
    "Modern European",
    "English",
    "Asian",
    "Fusion / Eclectic",
    "Latin American",
    "Brazilian Steakhouse",
    "Hawaiian",
    "Provencal",
    "Pan-Asian",
    "Irish",
    "Scandinavian",
    "Creole",
    "American",
    "Moroccan",
    "Southern",
    "Greek",
    "Gastro Pub",
    "Northwest",
    "Organic",
    "Southwest",
    "Pizzeria",
    "African",
    "Cajun",
    "Continental",
    "Argentinean",
    "Contemporary American",
    "Burgers",
    "British",
    "Contemporary Asian",
    "Persian",
    "Turkish",
    "Dim Sum",
    "European",
    "South Indian",
    "Chinese",
    "Contemporary European",
    "Caribbean",
    "Portuguese",
    "Basque",
    "Barbecue",
    "Vietnamese",
    "Creole / Cajun / Southern",
    "Beer Garden",
    "Mediterranean",
    "German",
    "French",
    "Japanese",
    "Mexican",
    "Afternoon Tea",
    "Latin / Spanish",
    "Italian",
    "Tapas / Small Plates",
    "French American",
    "Brewery",
    "Cuban",
    "Seafood",
    "Bar / Lounge / Bottle Service",
    "Pacific Rim",
    "Global, International",
    "Contemporary Italian",
    "Steakhouse",
    "Steak",
    "Bistro",
    "Thai",
    "Tex-Mex",
    "Contemporary French / American",
    "Californian",
    "Sushi",
    "Comfort Food",
    "Spanish",
    "Breakfast",
    "International",
    "Contemporary French",
    "Indian",
    "Belgian",
    "South American"
  ]
  ]]);

